build:
  only:
    - tags
  image: node:15
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    expire_in: 30 min
    paths:
      - dist

deploy:
  only:
    - tags
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - rsync -rav -e "ssh -p $SSH_PORT -o UserKnownHostsFile=$SSH_KNOWN_HOSTS" --delete dist/ deploy@$SERVER_URL:$DEPLOY_LOCATION
