# Needed for docker build step
image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  DOCKER_IMAGE_NAME: 768687622477.dkr.ecr.eu-central-1.amazonaws.com/homepage:latest
  DOCKER_REGISTRY_URL: 768687622477.dkr.ecr.eu-central-1.amazonaws.com

stages:
  - build
  - deploy
  - check

build_image:
  stage: build

  image: docker:git
  services:
      - docker:dind

  only:
    - tags

  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli

  script:
    - command=`aws ecr get-login --no-include-email --region eu-central-1`
    - eval "$command"
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME

  when: always

  allow_failure: false

deploy_aws:
  stage: deploy
  image: ruby:2.1

  only:
    - tags

  before_script:
    # Generate SSH key
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - commands="set -x && cd /home/ubuntu/Container && git fetch && git reset --hard && git pull && bash -x ci-install.sh"
    - ssh ubuntu@${SERVER_URL} ${commands}

  allow_failure: false

  variables:
    GIT_STRATEGY: none

check_deployment:
  stage: check
  image: ruby:2.1

  only:
    - tags

  script:
    - curl -s -f https://finkmartin.com > /dev/null

  allow_failure: false

  when: on_success

  variables:
    GIT_STRATEGY: none
